### PR TITLE
rename repo to opensource.osu.edu

### PR DESCRIPTION
**Pull request by egladman**
rename github repository from `open-source-club-website` to `opensource.osu.edu`

todo
- [x] rename baseurl variable in js
- [ ] correct github repository link

### CODE REVIEW

**Comment by Nefari0uss** [comment]
@OSUOSC/website-team ~ You should all be aware of this.

**Comment by J3RN** [comment]
I mean, sure. Go for it.

**Comment by egladman** [comment]
i've had an issue open for awhile #188

**Comment by moore3071** [comment]
I support changing the repo name, but I'd prefer the simple name of 'website' as earlier suggested in #188. Also note that the old remotes won't break given this page due to Github's awesomeness unless we put another repo in the org with the old name.

**Comment by egladman** [comment]
instead of fixing the merge conflict, i went ahead and pushed the changes to master. The repo has been renamed.

**Pull request closed without merging**
