### PR TITLE
Updated officers for next year

### PR DESCRIPTION
**Pull request by moore3071**
Officer's list for 2016-2017 added. Merge must later

@OSUOSC/website-team

### CODE REVIEW

**Comment by egladman** [comment]
@moore3071 good idea adding our irc nicks

**Comment by J3RN** [comment]
I'm not sure, but isn't EDT's first name "John" instead of "Jon"?

**Comment by egladman** [comment]
@J3RN yeah your right. I just checked his [github profile](https://github.com/haumea11)

**Comment by benlk** [comment]
Make sure to update the #osuosc channel taxonomy, too, please. 

```
/msg chanserv info #osuosc
12:43:46 freenode  -┤ ChanServ (ChanServ@services.): Information on #osuosc:
12:43:46 freenode  -┤ ChanServ (ChanServ@services.): Founder    : yano
12:43:46 freenode  -┤ ChanServ (ChanServ@services.): Registered : Sep 30 14:06:43 2009 (6y 28w 1d ago)
12:43:46 freenode  -┤ ChanServ (ChanServ@services.): Mode lock  : +ntFC-k
12:43:46 freenode  -┤ ChanServ (ChanServ@services.): URL        : https://opensource.osu.edu
12:43:46 freenode  -┤ ChanServ (ChanServ@services.): Entrymsg   : Welcome to The Ohio State University Open Source
                      Club IRC channel | Club website: https://opensource.osu.edu/ | Rules:
                      https://opensource.osu.edu/irc-rules | This channel is logged:
                      https://opensource.osu.edu/logread | For more information '/msg chanserv taxonomy #osuosc' 
12:43:46 freenode  -┤ ChanServ (ChanServ@services.): Metadata   : Campus = The Ohio State University Main Campus
12:43:46 freenode  -┤ ChanServ (ChanServ@services.): Metadata   : Faculty-Advisor = Shaun Rowland
12:43:46 freenode  -┤ ChanServ (ChanServ@services.): Metadata   : Logs = https://opensource.osu.edu/logread
12:43:46 freenode  -┤ ChanServ (ChanServ@services.): Metadata   : Office-Location = Caldwell Labs 112F
12:43:46 freenode  -┤ ChanServ (ChanServ@services.): Metadata   : President = Chris Wallace
12:43:46 freenode  -┤ ChanServ (ChanServ@services.): Metadata   : Treasurer = Nikit Malkan
12:43:46 freenode  -┤ ChanServ (ChanServ@services.): Metadata   : Vice-President = George Kvaratkshelia
12:43:46 freenode  -┤ ChanServ (ChanServ@services.): Flags      : KEEPTOPIC GUARD
12:43:47 freenode  -┤ ChanServ (ChanServ@services.): *** End of Info ***
```

**Comment by Nefari0uss** [comment]
@egladman We used to have nicks on the old website. I noticed they were missing on the new one so I told @moore3071 as many as I could remember. I think it's a nice touch that we have.

@benlk ~ Something to let @myano know.

**Pull request merged**
