### PR TITLE
Package manager talk

### PR DESCRIPTION
**Pull request by moore3071**
@OSUOSC/officers, double check that everything about the election is right.

### CODE REVIEW

**Comment by keeakita** [comment]
I'm not sure why the build is failing, but I don't want to merge this until I've tested it locally. I'll let you know when I've had a chance to cherrypick and check it out

**Comment by keeakita** [comment]
AFAICT This appears to be a regression not related to your commit. I'm looking into it, but would prefer to get that fixed before I merge anything new.

**Comment by keeakita** [comment]
I found and fixed the unrelated build issue (5dc82964726441e5d87ff930592580b7b0121730). I've manually verified this PR builds properly so I'm merging it even with the CI failing.

**Comment by egladman** [comment]
@oslerw thanks for taking care of it. it was on my list of things todo today

**Pull request merged**
