### PR TITLE
License meeting announcement

### PR DESCRIPTION
**Pull request by moore3071**
Added a post for the license meeting, and added it to the semester calendar.

### CODE REVIEW

**Comment by moore3071** [comment]
Oops, I wrote on your posts oslerw. You can tell I don't do a lot of pull requests. But, anyways, I followed the previous posts as an example for line length, but we can switch to an 80 char wrap.

For the end, I avoided such a signature in this post as I went with more of the royal we, and referred to myself in the third person in the post. I could put some other signature:

```
-- OSC staff
```

**Comment by keeakita** [comment]
That's fine. I noticed that some of the posts Eli wrote also don't wrap, and the sig is optional. This is good to accept.

**Comment by egladman** [comment]
why am i just now hearing about text not wrapping. make an issue

**Comment by keeakita** [comment]
Sorry, that wasn't meant to be a bad thing, I just didn't notice your posts weren't wrapped and thought we had a convention we don't actually have. If you want we can make it a convention, I can whip up a script that fixes things. I'll make an issue.

**Pull request merged**
