### PR TITLE
Added MS talk to schedule

### PR DESCRIPTION
**Pull request by moore3071**
Fixes # .
## 
## 

@OSUOSC/website-team

### CODE REVIEW

**Comment by keeakita** [comment]
This is a little pedantic, but branding wise the "s" in "Microsoft" is lower case

**Comment by moore3071** [comment]
My bad, I'll fix that

**Comment by J3RN** [comment]
@oslerw @moore3071 I think you guys mean "M$"

**Comment by Nefari0uss** [comment]
Apparently I self assigned this?

**Comment by moore3071** [comment]
@Nefari0uss, I assigned you since I wanted you to get an eye on it since you've been the one talking to MS.

**Comment by keeakita** [comment]
Oops

Nikit, let me know if you think it should be changed

**Comment by Nefari0uss** [comment]
This is probably good for now. I won't have more info until atleast a day or two. I was curious b/c my app said this was `self-assigned` over `assigned`.

**Pull request merged**
