### PR TITLE
Site services status update blog post

### PR DESCRIPTION
**Pull request by benlk**
Changes proposed in the pull request:
- a post explaining what happened to club servers, what their status is, and what the future holds.

As I wrote in my email to officers:

> I've been bugging @smacz42  and other officers (but primarily smacz) since the disruption for a mechanism by which updates on services recovery could be posted on the club website, possibly including starting a whole separate website. Andrew called me out on that today: I had been asking for messaging methods without asking for the status, and asking for resolution timelines without asking about the reasons for the issues.

> I was wrong. I should've asked different questions, and not treated the club servers like a service the club was obligated to provide to its present and past members. And instead of pestering people for updates, I should've worked to understand the problem, and to explain it to myself and other club users. My approach was wrong, and I apologize.

> As part of making up for that, I'd like to write a post for the club website that explains the status of club services, the problems and their causes. If any of you are open to this, I have a few questions to start the conversation.

I do want to better understand the problem. This pull request introduces the bare bones of the post necessary to get it to render, but doesn't have any more content than an outline of what I hope it could cover. I'll be adding to it as I better understand the problem and history.

If you have information to ontribute, you can get in touch with me in this PR, on IRC under the handle `Boom_Farmer`, or by email at keith.146.

@OSUOSC/website-team

### CODE REVIEW

**Comment by smacz42** [comment]
Let me know where you need more details.

> During the summer of 2017, the officers made a point of upgrading all of the servers to the latest stable version. During the course of that process, the virtualization host was upgraded and rebooted. This combination exposed long-standing issues with the hard drive - like corrupted sectors and unreadable sections of the disk. This resulted in missing files in almost all VMs. While looking at the backups of the VMs, we realized that they were incomplete as the disc sections were corrupted before the backups were attempted, which corrupted the preliminary backups that were made before the upgrades.
>
> Several methods of disc recovery were attempted with ddrescue, but it was ultimately determined that the disc was unrecoverable. Seeing as there are backups of most of the VMs to the point where they are potentially recreatable, but not able to be restored, we should be able to put together a network similar to what was available before, minus a mail service, which is to be handled in the future with the opensource mailing list.
>
> We plan on hosting several other services in addition to the website, such as a riot homeserver, and several others. However that would be on additional VMs. For the time being, there is only one server (Turing, the physical host) that is serving the website. There is no user accounts set up yet, however all the files from previous users' home directories are still intact as they were on our storage server (Stallman) instead of the failed server. They will be provided on request of any previous member, however they are not available for access at this time.

**Comment by benlk** [comment]
> They will be provided on request of any previous member, however they are not available for access at this time.

What's the request process? Should members just ask an officer (link here), or is there a dedicated point-of-contact for acquiring files? How will files be provided? 

What can club members/alumni/interested corporate sponsors do to help?

**Comment by smacz42** [comment]
Since there are no user accounts active at the moment, the files would have to be requested by someone who has access to the local administrative account, which for the time being is EDT and myself. There should be some sort of informal verification process such as a request coming from a previously established account, such as an email address or IRC handle that had been used in the past.

At that point, the files can be transferred whichever way is easiest for the user.

**Comment by benlk** [comment]
I'm reasonably-certain that most former users have PGP keys; they could send you emails signed with a known key or work out some other suitable proof-of-identity.

What can people do to help with the upgrade process, or with the club in general? ... that might be its own blog post, though.

**Comment by smacz42** [comment]
Since the install on the physical server is eventually meant to be a hypervisor, the software installed on it should be kept to a minimum. The biggest blocks are administrative ones, namely ETS. If we were setting up a colo, we'd already have a blog, a wiki, a matrix homeserver, and a jumphost to administer the five or so database servers powering the network.

However, if anyone has any pull with ETS that would be a thread to start pulling at.

**Pull request closed without merging**
