### PR TITLE
Post for Nick's FreeBSD talk posted

### PR DESCRIPTION
**Pull request by moore3071**
Adds Nick's post for his FreeBSD talk.

### CODE REVIEW

**Comment by egladman** [comment]
**Friendly Notice**

Future attempts to merge a post that isn't generated by [newPost.rb](https://github.com/OSUOSC/open-source-club-website/blob/master/_helpers/newPost.rb) will be rejected without warning. Using the generated post eliminates potential build issues.

**Comment by egladman** [comment]
@moore3071 you shouldn't manually change `config.yml`. `next_meeting_date` gets updated during the build process (which you would have known if you cloned the repo locally)

**Comment by keeakita** [comment]
I'm merging this since it looks and builds fine, but we really should talk about `config.yml`. If the file has portions that are auto-generated, then they should either:
1. Not be checked into git and stored in a different, gitignored file
2. Included in the commit, such that building the site will not cause the repository to appear dirty
3. Automatically removed after the build is finished

The repo shouldn't be dirty just by building, that's encourages accidents like committing changes unintentionally.

**Comment by egladman** [comment]
@oslerw i made #211 in response to your comment

**Pull request merged**
